# ansible-vault encrypt ./inventory/host_vars/example_host/example_secret.yaml

# Example Secret File for Host
# directory name must match the host name in the inventory/hosts.yaml file

---
ansible_host: remote_host_or_ip
ansible_port: 22
ansible_user: remote_username_here
ansible_become_pass: "remote_sudo_password_here"
