---
# tasks file for apt

- name: Check if a reboot is needed
  ### cat /var/run/reboot-required
  tags: ["reboot-required"]
  become: true
  stat:
    path: "{{ role_default_reboot_required_file }}"
  register: local_reboot_required

- name: Reboot the system
  ### sudo reboot
  tags: ["reboot"]
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting the system"
    reboot_timeout: 300
    connect_timeout: 5
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when:
    - local_reboot_required.stat.exists
